-- 코드를 입력하세요
WITH CTE as(
SELECT PRODUCT_ID, SUM(SALES_AMOUNT) as tt
FROM OFFLINE_SALE
GROUP BY PRODUCT_ID
)

SELECT PRODUCT_CODE, tt * price as SALES
FROM PRODUCT as p
JOIN CTE as c
ON p.PRODUCT_ID = c.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE ASC
