-- 코드를 입력하세요
WITH info AS (SELECT ci.CAR_ID, CAR_TYPE, DAILY_FEE FROM CAR_RENTAL_COMPANY_CAR as ci
WHERE CAR_TYPE IN ('세단', 'SUV') and
CAR_ID NOT IN (SELECT CAR_ID 
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY as ch
      WHERE START_DATE <= '2022-11-30' and END_DATE >= '2022-11-01'))

             
SELECT CAR_ID, CAR_TYPE, FEE FROM (SELECT CAR_ID, cd.CAR_TYPE, FLOOR(DAILY_FEE * 30 * (100-discount_rate) / 100) as FEE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN as cd
JOIN info 
ON info.CAR_TYPE = cd.CAR_TYPE
WHERE duration_type = '30일 이상') as cnt
WHERE FEE >= 500000 and FEE < 2000000
ORDER BY FEE DESC,  CAR_TYPE ASC,  CAR_ID DESC