-- 코드를 입력하세요
WITH CTE AS (SELECT CAR_ID, DATEDIFF(END_DATE, START_DATE) + 1 as diff
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY)

SELECT CAR_ID, round(AVG(diff), 1) AS AVERAGE_DURATION 
FROM CTE
GROUP BY CAR_ID
HAVING round(AVG(diff), 1) >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC
