-- 코드를 작성해주세요
SELECT ROUTE, concat(round(SUM(D_BETWEEN_DIST), 1), 'km') as TOTAL_DISTANCE, concat(round(AVG(D_BETWEEN_DIST), 2), 'km') as AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE 
GROUP BY LINE, ROUTE 
ORDER BY SUM(D_BETWEEN_DIST) DESC