-- 코드를 입력하세요
WITH CTE AS (
    SELECT HISTORY_ID, CAR_ID, DATEDIFF(END_DATE, START_DATE) + 1 as DIFF,
    CASE 
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN 15
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN 8
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN 5
        ELSE 0
    END AS discount_rate
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE CAR_ID IN (SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_CAR 
    WHERE CAR_TYPE = '트럭')
)

SELECT HISTORY_ID, round(daily_fee * DIFF * (100-discount_rate) / 100, 0) as FEE 
FROM CTE
JOIN CAR_RENTAL_COMPANY_CAR as cr
ON CTE.CAR_ID = cr.CAR_ID
ORDER BY FEE DESC, HISTORY_ID DESC



 