-- 코드를 작성해주세요
SELECT ch.ID, ch.GENOTYPE, pr.GENOTYPE as PARENT_GENOTYPE 
FROM ECOLI_DATA as ch
JOIN ECOLI_DATA as pr
ON ch.PARENT_ID = pr.ID
WHERE ch.GENOTYPE & pr.GENOTYPE = pr.GENOTYPE
ORDER BY ch.ID