-- 코드를 작성해주세요
SELECT YEAR, (SIZE-SIZE_OF_COLONY) as YEAR_DEV, ID FROM ECOLI_DATA 
JOIN
(SELECT YEAR(DIFFERENTIATION_DATE) as YEAR, MAX(SIZE_OF_COLONY) as SIZE FROM ECOLI_DATA 
GROUP BY YEAR(DIFFERENTIATION_DATE)) as max_val
ON YEAR(DIFFERENTIATION_DATE) = max_Val.YEAR
ORDER BY YEAR, YEAR_DEV
