-- 코드를 입력하세요
SELECT TITLE, BD.BOARD_ID, REPLY_ID, RE.WRITER_ID, RE.CONTENTS, DATE_FORMAT(RE.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM (SELECT * FROM USED_GOODS_BOARD WHERE CREATED_DATE >= '2022-10-01' AND CREATED_DATE < '2022-11-01') BD
JOIN USED_GOODS_REPLY RE
ON BD.BOARD_ID = RE.BOARD_ID
ORDER BY RE.CREATED_DATE ASC, BD.TITLE;



