-- 코드를 작성해주세요
WITH CTE as (SELECT DEPT_ID, round(avg(SAL), 0) as AVG_SAL
FROM HR_EMPLOYEES 
GROUP BY DEPT_ID)

SELECT CTE.DEPT_ID, HD.DEPT_NAME_EN, AVG_SAL FROM CTE
JOIN HR_DEPARTMENT as HD
ON CTE.DEPT_ID = HD.DEPT_ID
ORDER BY AVG_SAL DESC