-- 코드를 입력하세요
WITH CTE as(   
    SELECT BOARD_ID
    FROM USED_GOODS_BOARD
    ORDER BY VIEWS DESC
LIMIT 1)

SELECT CONCAT('/home/grep/src/', CTE.BOARD_ID, '/', GI.FILE_ID, GI.FILE_NAME, GI.FILE_EXT) as FILE_PATH
FROM CTE
JOIN USED_GOODS_FILE  as GI
ON CTE.BOARD_ID = GI.BOARD_ID
ORDER BY GI.FILE_ID DESC