-- 코드를 입력하세요
SELECT CATEGORY, sum(SALES) as TOTAL_SALES
FROM BOOK as b
JOIN BOOK_SALES as bl
ON b.BOOK_ID = bl.book_ID
WHERE YEAR(SALES_DATE) = 2022 and MONTH(SALES_DATE) = 1
GROUP BY CATEGORY
ORDER BY CATEGORY ASC